### ISSUE TITLE
requirements/use.txt missing

### ISSUE THREAD

**Issue by Glueon** [HTTPretty/HTTPretty#3]
As with the original git repo it's impossible to install httpretty directly from git.

```
pip install git+https://github.com/HTTPretty/HTTPretty.git
Collecting git+https://github.com/HTTPretty/HTTPretty.git
  Cloning https://github.com/HTTPretty/HTTPretty.git to /tmp/pip-ulpoh1z4-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-ulpoh1z4-build/setup.py", line 60, in parse_requirements
        requirements = [req.strip() for req in local_file(path).splitlines()]
      File "/tmp/pip-ulpoh1z4-build/setup.py", line 81, in <lambda>
        os.path.join(os.path.dirname(__file__), *f), encoding='utf-8').read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-ulpoh1z4-build/test-requirements.txt'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-ulpoh1z4-build/setup.py", line 97, in <module>
        tests_require=parse_requirements('test-requirements.txt'),
      File "/tmp/pip-ulpoh1z4-build/setup.py", line 62, in parse_requirements
        raise RuntimeError("Couldn't find the `requirements/use.txt' file :(")
    RuntimeError: Couldn't find the `requirements/use.txt' file :(

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ulpoh1z4-build
```

**Comment by KarelJakubec** [comment]
The file is not missing, it is empty, however I experience the same problem.

It is possible to install requirements using pip manually - pip install -r "requirements/dev.txt" or so. The correct fix should probably be to realize which requirements from "dev.txt" and "test.txt" are needed for use and move them. Would you mind providing patch? :)
