### ISSUE TITLE
Can't install httpretty without a properly set up shell session

### ISSUE THREAD

**Issue by EliRibble** [HTTPretty/HTTPretty#8]
Here's the output of me installing httpretty with pip via salt, which does not establish a shell:

```
Downloading/unpacking HTTPretty==0.8.10 (from sepiida==2.20->vision)
  Running setup.py (path:/opt/authentise/vision/ve/build/HTTPretty/setup.py) egg_info for package HTTPretty
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/opt/authentise/vision/ve/build/HTTPretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/opt/authentise/vision/ve/build/HTTPretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/opt/authentise/vision/ve/build/HTTPretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/opt/authentise/vision/ve/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/opt/authentise/vision/ve/build/HTTPretty/setup.py", line 86, in <module>

    version=read_version(),

  File "/opt/authentise/vision/ve/build/HTTPretty/setup.py", line 46, in read_version

    finder.visit(ast.parse(local_file('httpretty', '__init__.py')))

  File "/opt/authentise/vision/ve/build/HTTPretty/setup.py", line 78, in <lambda>

    open(os.path.join(os.path.dirname(__file__), *f)).read()

  File "/opt/authentise/vision/ve/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
```

**Comment by yarikoptic** [comment]
sorry about a bit of confusion -- this repository is not "official" httpretty.  see https://github.com/gabrielfalcao/HTTPretty/issues/272 for more info on that.  meanwhile -- there was activities upstream and this issue seems to be fixed at least in current master, since `LANG=C pip install https://github.com/gabrielfalcao/HTTPretty/archive/master.zip` does work.  note that upstream also ruled out 3.4, 3.5 as officially supported atm

**Comment by EliRibble** [comment]
Oh, I knew this wasn't the 'official' repo. I've been watching the work you guys have been doing and had more hope that if I created an issue and then solved it myself that this project would move forward than if I had posted in the gabrielfalcao repo. Thanks for the pointer.

**Comment by yarikoptic** [comment]
well -- the point is that the issue seems to be solved already. I have just submitted another PR "upstream" for 2 tiny hopefully addressing few more issues with python 3.4 ... so may be we will arrive somewhere sometime ;)
